DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE IF NOT EXISTS products
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name       VARCHAR(50)                                          NOT NULL,
    price      DECIMAL(100, 2)                                      NOT NULL
);